# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=30)),
                ('cast', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('adult', models.BooleanField(default=False)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
